DROP TABLE IF EXISTS users, items, bookings, requests, comments;

CREATE TABLE IF NOT EXISTS users
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name     VARCHAR(40) NOT NULL,
    email    VARCHAR(60) NOT NULL,

    constraint users_pk PRIMARY KEY (id),
    constraint uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name     VARCHAR(40) NOT NULL,
    description    VARCHAR(200) NOT NULL,
    is_available BOOLEAN NOT NULL,
    owner_id BIGINT,
    request_id BIGINT,

    constraint items_pk PRIMARY KEY (id),
    constraint fk_owner_id FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP WITH TIME ZONE NOT NULL,
    item_id BIGINT,
    booker_id BIGINT,
    status VARCHAR(10) NOT NULL,

    constraint booking_pk PRIMARY KEY (id),
    constraint fk_booker_id FOREIGN KEY (booker_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    text VARCHAR(200) NOT NULL,
    item_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    created TIMESTAMP WITH TIME ZONE,

    constraint comment_pk PRIMARY KEY (id),
    constraint fk_item_id FOREIGN KEY (item_id) REFERENCES items (id),
    constraint fk_author_id FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(200) NOT NULL,
    requestor_id BIGINT NOT NULL,
    created TIMESTAMP WITH TIME ZONE,

    constraint request_pk PRIMARY KEY (id),
    constraint fk_requestor_id FOREIGN KEY (requestor_id) REFERENCES users (id)
);




